- name: Update APT package cache
  become: true
  apt: update_cache=yes

- name: Install/upgrade dependencies
  become: true
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ olsrd_build_dependencies }}"

- name: "Create {{ olsrd_dir }}"
  become: true
  file:
    path: "{{ olsrd_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: sudo
